version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: pfal-mosquitto
    ports:
      - "1883:1883"    # MQTT
      - "9001:9001"    # Websockets (optional)
    volumes:
      - ./config/mosquitto/config:/mosquitto/config:ro
      - ./config/mosquitto/data:/mosquitto/data
      - ./config/mosquitto/log:/mosquitto/log
    restart: unless-stopped
